In [4]:
import pennylane as qml
import numpy as np

In [14]:
n = 3
dev = qml.device('default.qubit', wires=n)

In [43]:
def GivensQubitUnitary(p, q, theta):
    assert p < q
    U = np.identity(2**n)
    U[p,p] = np.cos(theta/2)
    U[q,q] = np.cos(theta/2)
    U[q,p] = -np.sin(theta/2)
    U[p,q] = np.sin(theta/2)
    return qml.QubitUnitary(U, wires=range(n))

In [47]:
@qml.qnode(dev)
def circuit_a():
    GivensQubitUnitary(0,4,np.pi)
    return qml.state()

In [49]:
circuit_a()

tensor([ 6.123234e-17+0.j,  0.000000e+00+0.j,  0.000000e+00+0.j,
         0.000000e+00+0.j, -1.000000e+00+0.j,  0.000000e+00+0.j,
         0.000000e+00+0.j,  0.000000e+00+0.j], requires_grad=True)

In [50]:
qml.matrix(GivensQubitUnitary(0,1,np.pi))

array([[ 6.123234e-17,  1.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00],
       [-1.000000e+00,  6.123234e-17,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  1.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  1.000000e+00,
         0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         1.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  1.000000e+00,  0.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.000000e+00,  0.000000e+00,
         0.000000e+00,  0.000000e+00,  1.000000e+00,  0.000000e+00],
       [ 0.000000e+00,  0.000000e+00,  0.

In [265]:
def Flip2(p, q, wires=[0,1]):
    assert p < q
    if p == 0:
        if q == 1:
            return qml.ctrl(qml.PauliX(wires[1]), (wires[0]), control_values=(0))
        elif q == 2:
            return qml.ctrl(qml.PauliX(wires[0]), (wires[1]), control_values=(0))
        elif q == 3:
            qml.CNOT(wires=wires),
            qml.PauliX(wires=[wires[0]]),
            qml.CNOT(wires=[wires[1], wires[0]]),
            qml.CNOT(wires=wires)
            return
    elif p == 1:
        if q == 2:
            return qml.SWAP(wires=wires)
        elif q == 3:
            return qml.ctrl(qml.PauliX(wires[1]), (wires[0]), control_values=(1))
    elif p == 2:
        if q == 3:
            return qml.CNOT(wires=wires)
            
    raise Exception("p or q is out of bounds")

def Givens2(p, q, theta, wires=[0,1]):
    assert p < q
    if p == 0:
        if q == 1:
            qml.PauliX(wires[1])
            qml.CRY(theta, wires=wires)
            qml.PauliX(wires[1])
            return
        elif q == 2:
            qml.PauliX(wires[0])
            qml.CRY(theta, wires=[wires[1], wires[0]])
            qml.PauliX(wires[0])
            return
        elif q == 3:
            qml.PauliX(wires[1])
            qml.CNOT(wires=wires)
            qml.CRY(theta, wires=wires)
            qml.CNOT(wires=wires)
            qml.PauliX(wires[1])
            return
    elif p == 1:
        if q == 2:
            qml.CNOT(wires=wires)
            qml.CRY(theta, wires=[wires[1], wires[0]])
            qml.CNOT(wires=wires)
            return
        elif q == 3:
            return qml.CRY(theta, wires=[wires[1], wires[0]])
    elif p == 2:
        if q == 3:
            return qml.CRY(theta, wires=wires)
            
    raise Exception("p or q is out of bounds")

def GivensN(p, q, theta):
    """
    TODO
    """
    pass

In [272]:
dev = qml.device('default.qubit', wires=2)

@qml.qnode(dev)
def circuit_b():
    qml.BasisState([1,0], wires=range(2))
    Flip2(2,3)
    return qml.state()

circuit_b()

tensor([0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j], requires_grad=True)